services:
  postgres:
    image: postgres:16
    container_name: task_manager_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: task_manager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: